services:
  web: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    container_name: replyai-frontend
    networks:
      - replyai-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    container_name: replyai-api
    networks:
      - replyai-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  migrate:
    build:
      context: ./backend
      dockerfile: migrate.Dockerfile
    depends_on:
      - db
    container_name: replyai-migrate
    networks:
      - replyai-network
    # restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    container_name: replyai-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - replyai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  replyai-network:
    driver: bridge
    