import Container from "@/components/container";
import { ExternalLink } from "@/components/external-link";
import { ScrollView, Text, View } from "react-native";

export default function Home() {
    return (
        <Container>
        <View>
           <ScrollView>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            <View>
                <Text>Home</Text>
            </View>
            </ScrollView> 
        </View>
</Container>
    );
}