"""feat: add auto_copy column to settings

Revision ID: 1f679fadc3d3
Revises: 9ea464b64d0c
Create Date: 2026-08-01 22:12:52.099294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f679fadc3d3'
down_revision: Union[str, Sequence[str], None] = '9ea464b64d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('auto_copy', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'auto_copy')
    # ### end Alembic commands ###
