"""fix: typo on replies table column transcript

Revision ID: 9ea464b64d0c
Revises: abde98ae44a3
Create Date: 2026-07-16 23:20:34.533528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea464b64d0c'
down_revision: Union[str, Sequence[str], None] = 'abde98ae44a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('transcript', sa.String(length=5000), nullable=False))
    op.drop_column('replies', 'transcipt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('transcipt', sa.VARCHAR(length=5000), autoincrement=False, nullable=False))
    op.drop_column('replies', 'transcript')
    # ### end Alembic commands ###
